Samples authorization
SciCatProject/backend pull request #1044
Opened 2024-02-05 14:28 UTC by nitrosx

## Description
This PR includes a review and following refactor of the Samples Authorization. It also includes authorization API tests to cover all the known cases.
Please refer to the documentation regarding the new settings

## Motivation
The SciWyrm project notified the BE team that an account whose group belonged to "Sample Groups" was not able to create samples.
This sparked the review of the current tests and cased covered, which lead to the realization that new authorization tests were needed, together with some code refactoring.

## Fixes:
* all existing test as ingestor account has been renamed adminIngestor
* added SampleAuthorization tests
* refactor how test functional accounts are used in tests

## Tests included/Docs Updated?

- [x] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [x] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?

2024-02-14 08:25 UTC, bpedersen2 requested changes

2024-02-14 08:25 UTC, bpedersen2 commented on test/CheckDifferentDatasetTypes.js
> +        username: "adminIngestor",
use  TestData instead of hardcoding it here?

2024-02-14 08:25 UTC, bpedersen2 commented on test/DatasetLifecycle.js
> +        password: "13f4242dc691a3ee3bb5ca2006edcdf7",
TestData ?

2024-02-14 08:25 UTC, bpedersen2 commented on test/DerivedDataset.js
> +        password: "13f4242dc691a3ee3bb5ca2006edcdf7",
TestData ?

2024-02-19 16:50 UTC, nitrosx commented on test/CheckDifferentDatasetTypes.js
> +        username: "adminIngestor",
I found the solution and it will implemented for the samples first.

2024-02-19 16:51 UTC, nitrosx commented on test/DatasetLifecycle.js
> +        password: "13f4242dc691a3ee3bb5ca2006edcdf7",
I will make sure that it is solved

2024-02-19 16:51 UTC, nitrosx commented on test/DerivedDataset.js
> +        password: "13f4242dc691a3ee3bb5ca2006edcdf7",
Same as above

2024-02-28 13:11 UTC, Junjiequan approved these changes
Left a few comments on the minor things.
As long as all the test passes, I'm fine with this PR to get merged

2024-02-28 13:11 UTC, Junjiequan commented on src/datasets/datasets.controller.ts
> +  // )
This should be removed instead of commenting out.
We don't use Action.Read, DatasetClass authentication any more

2024-02-28 13:11 UTC, Junjiequan commented on test/Sample.js
> +//      .expect("Content-Type", /json/)
What's the reason commenting out .expect("Content-Type", /json/)

2024-02-28 16:04 UTC, nitrosx commented on src/datasets/datasets.controller.ts
> +  // )
Good catch. Resolved!!!

2024-02-28 16:11 UTC, nitrosx commented on test/Sample.js
> +//      .expect("Content-Type", /json/)
no reason. reinstated.

2024-03-04 16:45 UTC, nitrosx commented
All the changes requested by @bpedersen2 have been implemented. I'm not sure why the PR is still blocked.
I am going ahead and merge it.

2024-03-04 16:46 UTC, merged