Allow user defined `id` field in `MeasurementPeriods`
SciCatProject/backend pull request #1274
Opened 2024-06-20 13:14 UTC by fpotier

#745

2024-06-24 15:17 UTC, nitrosx requested changes
@fpotier the code looks fine and it passes the test, so if we are in a hurry to get this feature in, I will be happy to approve it.
That said, I would like to propose two different approaches:
1. place the measurement period list in it's own collection with a proper schema, which will solve the unique id issue. 
2. expand the concept of proposal with proposal type, parent proposal, and metadata (similar to dataset scientificMetadata) which will allow to create a hierarchical structure of proposals entities which has at the root your proposal and under each visit (aka measurement period)

Let's discuss

2024-06-24 15:29 UTC, fpotier commented
@nitrosx Thanks, no hurry to merge it!
I'm okay with moving MeasurementPeriods to a dedicated collection but I'm not sure that the unique id issue would be solved.
Our user office uses a simple counter for each proposal (1..n), so in our case, we need uniqueness based on the proposal id. There can be an arbitrary number of period with id 1 as long as their proposal ids are different.

2025-03-24 14:03 UTC, nitrosx commented
@fpotier is this PR still relevant considering that proposals can now be hierarchical and, also, have a property type and metadata.

2025-03-24 14:16 UTC, fpotier commented
@nitrosx this PR and #1783 where for SOLEIL's proposal ingestion. Since I left, I don't know if this is still required or can be closed

2025-07-01 14:43 UTC, closed without merging