feat: make large file access warning text configurable with largeData…
SciCatProject/backend pull request #1517
Opened 2024-11-20 14:17 UTC by Junjiequan

…FileAccessInstruction.

## Description
Change for the https://github.com/SciCatProject/frontend/pull/1666

## Motivation

## Fixes

* Bug fixed (#X)

## Changes:

* changes made

## Tests included

- [ ] Included for each change/fix?
- [ ] Passing? 

## Documentation
- [ ] swagger documentation updated (required for API changes)
- [ ] official documentation updated

### official documentation info

2024-11-26 13:15 UTC, bpedersen2 commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
maxFileSizeWarning ?

2024-12-03 15:32 UTC, nitrosx commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
@bpedersen2 would `maxFileSizeMessage` be a better name?

2024-12-04 07:42 UTC, bpedersen2 commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
No, see the the src/config/frontend.config.json,  largeDataFileAccessInstructions seem unused.

2024-12-04 08:56 UTC, nitrosx commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
Good point. I did not see that entry.

2024-12-04 08:59 UTC, nitrosx requested changes

2024-12-04 08:59 UTC, nitrosx commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
@Junjiequan let's remove `maxFileSizeWarning` and use `largeDataFileAccessInstruction`

2024-12-04 08:59 UTC, nitrosx commented on src/config/frontend.config.json
> +  "maxFileSizeWarning": "Some files are above <maxDirectDownloadSize> and cannot be downloaded directly. These file can be downloaded via sftp host: <sftpHost> in directory: <sourceFolder>",
@Junjiequan let's rename `maxFileSizeWarning` to `largeDataFileAccessInstruction`

2024-12-13 10:59 UTC, Junjiequan commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
@nitrosx Are you sure about the renaming? FE change also needs to be changed then which was just merged before https://github.com/SciCatProject/frontend/pull/1666/files

2025-01-08 09:43 UTC, nitrosx commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
Keep `maxFileSizeWarning`

2025-01-08 09:43 UTC, nitrosx commented on CI/E2E/frontend.config.json
> +  "largeDataFileAccessInstruction": "",
...and remove `largeDataFileAccessInstruction`

2025-01-08 14:22 UTC, nitrosx approved these changes

2025-01-17 12:06 UTC, merged