Jobs RabbitMQ Action connection info should come from ConfigService
SciCatProject/backend pull request #1575
Opened 2024-12-17 13:06 UTC by despadam

## Description
Previously, all information needed to set up the Jobs RabbitMQ action would come from `jobConfig`.
A better approach is to split this information: connection config info should be in  `.env` file, and only the queue info in the `jobConfig` file.

## Motivation
Extract the info from `ConfigService` after the NestJS refactor.

## Changes
While NestJs offers a RabbitMQ microservice, unfortunately it does not cover all necessary options needed for Jobs. More specifically, we are configurating `exchange` and `key`, which is not offered by that library. So instead, we stick to using the `amqplib` library as before, but only request `queue`, `exchange` and `key` to be defined in `jobConfig`. Which means that the `.env` file should now look like this example for RabbitMQ Job Action to be set up properly:
```
RABBITMQ_ENABLED="yes"
RABBITMQ_HOSTNAME="rabbitmq"
RABBITMQ_PORT=5672
RABBITMQ_USERNAME="guest"
RABBITMQ_PASSWORD="guest"
```

2024-12-17 16:09 UTC, sbliven requested changes
This will create a new messagebroker instance for each action. I think it would be better to wrap this into a nest module so it can be shared.

AppModule also constructs a RabbitMQMessageBroker, coming from [@user-office-software/duo-message-broker](https://github.com/UserOfficeProject/user-office-lib) rather than `amqplib` directly. It seems to be ESS-specific functionality for their proposal system. I was going to suggest using the same broker instance for that too, but after looking at the code I'm not sure it would work. We should discuss that code with the ESS people, but perhaps not in this PR.

2024-12-17 16:09 UTC, sbliven commented on src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
> +        };
In v3 this was provided as a connection string, like "amqp://USER:PASS@HOST:PORT". Is splitting it into 5 env variables necessary?

2024-12-17 16:09 UTC, sbliven commented on src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
> +      this.configService.get<string>("rabbitMq.enabled") === "yes"
Use `mathjs.parseBool` for this

2024-12-17 16:30 UTC, despadam commented on src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
> +        };
Some of those variables are also used to configure the other RabbitMQ message broker in app.module. So for now I will leave this as is and later, when we have a discussion about that, we can bring this up.

2024-12-18 08:05 UTC, despadam commented on src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
> +      this.configService.get<string>("rabbitMq.enabled") === "yes"
I don't think that this exists, are you sure? So I just simplified the logic

2024-12-18 14:03 UTC, sbliven approved these changes
Looks good, thanks for the update!

2024-12-18 14:03 UTC, sbliven commented on src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
> +    this.rabbitMQService.sendMessage(this.queue, JSON.stringify(job));
We should double check that it's thread-safe. I think it should be ok since they aren't async.

2024-12-18 14:09 UTC, merged

2024-12-18 20:34 UTC, sbliven commented on src/common/rabbitmq/rabbitmq.service.ts
> +      Logger.error(error);
I would throw the error and log it higher up if needed.

2024-12-18 20:37 UTC, sbliven commented on src/common/rabbitmq/rabbitmq.service.ts
> +      Logger.error("RabbitMQ is not enabled.", "RabbitMQService");
What's the expected behavior if they don't have RabbitMQ enabled? I think the service gets instantiated either way. Maybe the constructor should succeed (without logging) but there should be an error if connect() is called or if a rabbitmqaction is created.

2024-12-18 20:39 UTC, sbliven commented on src/common/rabbitmq/rabbitmq.service.ts
> +  sendMessage(queue: string, message: string) {
What happens if a message is sent without first calling connect? If they are always called in pairs would it make more sense to merge them into one method?

2024-12-18 20:39 UTC, sbliven commented on src/common/rabbitmq/rabbitmq.service.ts
> +      Logger.error(
As above, throw the error

2024-12-18 20:41 UTC, sbliven commented on src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
>      Logger.log(
Remove logging

2024-12-18 20:42 UTC, sbliven commented on src/config/job-config/actions/rabbitmqaction/rabbitmqaction.ts
> +    this.queue = options.queue;
should throw an error if rabbitMQ isn't enabled