test: add some extra tests for creating datasets with right access gr…
SciCatProject/backend pull request #910
Opened 2023-11-23 14:56 UTC by martin-trajanovski

…oups

## Description

Short description of the pull request

## Motivation

Background on use case, changes needed

## Fixes:

* Items added

## Changes:

* changes made

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?

2023-11-27 10:44 UTC, Junjiequan requested changes
I think there's room for test accuracy improvement with small changes

2023-11-27 10:44 UTC, Junjiequan commented on test/DatasetAuthorization.js
> +        res.statusCode.should.not.be.equal(200);
For invalid dataset creation, I'd suggest to use equal to 400 status, to make the test more precise.

2023-11-27 10:44 UTC, Junjiequan commented on test/DatasetAuthorization.js
> +        res.statusCode.should.not.be.equal(200);
These test cases should be part of authentication process, so  I'd suggest to use equal to 403 status for all the similar tests, to make the test more precise.

2023-11-28 09:22 UTC, Junjiequan approved these changes
Looks good to me

2023-11-28 12:02 UTC, nitrosx approved these changes

2023-11-28 12:02 UTC, merged