Issue 924: add support for arrays in scientificMetadata
SciCatProject/backend pull request #925
Opened 2023-11-30 15:12 UTC by jkotan

## Description

It resolves #924  by adding support for arrays in scientificMetadata

## Motivation

At DESY we often use a list to store vectors

## Changes:

* I add `convertArrayToSI` function which is called by `appendSIUnitToPhysicalQuantity`

2023-12-01 06:55 UTC, jkotan commented
Hi,
on the other hand if you don't want to store additional SI values for array because it takes too much space, maybe it would be good to skip arrays conversion without throwing the error (as in the current code).

2023-12-01 08:34 UTC, jkotan commented
I've just added a workaround for #926

2023-12-04 09:46 UTC, bpedersen2 reviewed
Except  for some additional  comment requests, this looks fine

2023-12-04 09:46 UTC, bpedersen2 commented on src/common/utils.ts
> +    const newUnit = unit(inputUnit).toSI().toJSON().unit;
can add a comment for this workaround, so that we can easier find to roll back these changes once upstream mathjs has fixed that behaviour ( and if possible  reference a mathjs bug report as well)

2023-12-04 09:47 UTC, bpedersen2 requested changes
see my previous comments

2023-12-05 10:17 UTC, nitrosx reviewed
This looks fine to me.
I would suggest to add also the following:
- API tests to test specifically this feature
- address how the fullquery logic deals with this new type of metadata.

Potentially we could merge this PR, as long as we start working right away on the other two tasks right

2024-01-10 11:50 UTC, sbliven commented on src/common/utils.ts
> +export const convertArrayToSI = (
Can you add a docstring?

2024-01-10 14:22 UTC, jkotan commented on src/common/utils.ts
> +export const convertArrayToSI = (
Hello @sbliven, 
I'm not sure what should be in the docstring. In the case of `convertArrayToSI` the code does not contain the workaround. I think it is better to convert the unit only once and then apply it with use of `.to()` as it is in the code now. If you would like to execute `.toSI()` for every list item you convert the unit for each item so it does not seem to be optimal.

2024-01-19 08:30 UTC, bpedersen2 commented
Please check the frontend edit function as well ( it currently seems to truncate  the scientific metadata if it encounters an array in the values)!

2024-01-19 08:36 UTC, bpedersen2 commented on src/common/utils.ts
> +    const newUnit = unit(inputUnit).toSI().toJSON().unit;
#1005 bumped to version with fixed mathjs (see https://github.com/josdejong/mathjs/blob/develop/HISTORY.md#2024-01-12-1230) so we could drop the workaround now.

2024-01-19 08:37 UTC, jkotan commented
> Please check the frontend edit function as well ( it currently seems to truncate the scientific metadata if it encounters an array in the values)!

I think the frontend  has a separate repository so one need to open a ticket in the dedicated repository

2024-09-10 08:42 UTC, sbliven commented
What's the status of this PR?

2025-03-24 14:07 UTC, nitrosx commented
We should review this request given that now metadata should contain the range type.
Also, we need to define better the user case and make sure that related work is also done in the frontend

2025-11-06 13:35 UTC, Junjiequan commented
Hi, please confirm if this PR is still relevant within the next two weeks.
Otherwise, we’ll plan to close it to keep the repo tidy.

2025-11-24 09:00 UTC, closed without merging